# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
de:
  languageCode: de
  contentDir: content/de
  title: Baumtomographie
  params:
    description: Informationen zu aktuellen Studien über Arboristik und urbane Forstwirtschaft
  menu:
    main:
      - name: de
        url: '#about'
        weight: 1